// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_EXTXziwGjOcPtsa2GGbF0SDCFY95Oiw',
    appId: '1:940400654225:web:a4e7be6911fad570a9cc30',
    messagingSenderId: '940400654225',
    projectId: 'dream-logs',
    authDomain: 'dream-logs.firebaseapp.com',
    storageBucket: 'dream-logs.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCttzowAMW1jd9yyXKSG7U1ry_8jfoBEJY',
    appId: '1:940400654225:android:8da0677f5a0e0c2da9cc30',
    messagingSenderId: '940400654225',
    projectId: 'dream-logs',
    storageBucket: 'dream-logs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsLOJofXWVZwUeSCkoPLSwvTQ4bM91PfU',
    appId: '1:940400654225:ios:50fb6458716bd721a9cc30',
    messagingSenderId: '940400654225',
    projectId: 'dream-logs',
    storageBucket: 'dream-logs.firebasestorage.app',
    iosBundleId: 'com.dreamlogs.app',
  );
}
